name: File-to-link

on:
  workflow_dispatch:
    inputs:
      FILE_LINK:
        description: 'file link'
        required: true
        default: 'https://dlcdnets.asus.com/pub/ASUS/mb/14Utilities/Armoury_Crate_Full_Installation_Package.zip'

jobs:
  build:
    name: File downloader by ${{ github.actor }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Getting tools ready 
      run: |
        sudo apt install rar
        sudo apt install wget
    
    - name: Downloading file from Oreginal website
      run: |
        mkdir drive && cd drive
        wget ${{ github.event.inputs.FILE_LINK }}
        ls
        echo "FILE_ID=$(ls)" >> $GITHUB_ENV
    - name: Check file size
      run: |
        cd drive
        if [[ $(stat -c '%s' *.*) -gt 2147483648 ]]; then
        echo "The File is larger than 2GB"
        echo "FILE_SIZE=true" >> $GITHUB_ENV
        else
        echo "File is smaller than or equal to 2GB"
        echo "FILE_SIZE=false" >> $GITHUB_ENV
        fi
    - name: Processing Big File
      if: ${{ env.FILE_SIZE }} == 'true'
      run: |
        cd drive
        mv *.* Part.*
        rar a -v2000m Part.rar *
        ls -la
    - name: Processing Small File
      if: ${{ env.FILE_SIZE }} == 'false'
      run: |
        cd drive
        mv *.* archive.*
        rar a archive.rar *
        ls -la
    - name: Set Build Date 
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        
    - name: Upload to Github
      uses: softprops/action-gh-release@v1
      with:
        files: |
          drive/*.rar
        name: ${{ env.FILE_ID }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
