name: File-to-link

on:
  workflow_dispatch:
    inputs:
      FILE_LINK:
        description: 'file link'
        required: true
        default: 'https://dlcdnets.asus.com/pub/ASUS/mb/14Utilities/Armoury_Crate_Full_Installation_Package.zip'

jobs:
  build:
    name: File downloader by ${{ github.actor }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Getting tools ready 
      run: |
        sudo apt install p7zip-full
        sudo apt install wget
    
    - name: Downloading file from Oreginal website
      run: |
        mkdir drive && cd drive
        wget ${{ github.event.inputs.FILE_LINK }}
        ls
        echo "FILE_ID=$(ls)" >> $GITHUB_ENV
    - name: Processing File
      run: |
        cd drive
        7z a -v2g ${{ env.FILE_ID }}.7z ${{ env.FILE_ID }}
        rm ${{ env.FILE_ID }}
        ls -la
    - name: Set Build Date 
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        
    - name: Upload to Github
      uses: softprops/action-gh-release@v1
      with:
        files: |
          drive/*.*
        name: ${{ env.FILE_ID }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
